workflows:
  android-workflow:
    name: Android APK Build

    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Install Rust
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"

          rustc --version
          cargo --version

      - name: Install Rust Tools
        script: |
          export PATH="$HOME/.cargo/bin:$PATH"

          cargo install --force cargo-make
          cargo install --force cargo-lipo
          cargo install --force --locked duckscript_cli

      - name: Prepare AppFlowy
        script: |
          export PATH="$HOME/.cargo/bin:$PATH"

          cd frontend

          cargo make appflowy-flutter-deps-tools

      - name: Build APK
        script: |
          cd frontend/appflowy_flutter

          flutter pub get

          flutter build apk --debug

    artifacts:
      - frontend/appflowy_flutter/build/**/outputs/**/*.apk