workflows:
  android-workflow:
    name: Android Workflow

    environment:
      flutter: 3.27.4

    scripts:
      - name: Install Rust
        script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install Tools
        script: |
          cargo install cargo-make
          cargo install cargo-lipo

      - name: Flutter Dependencies
        script: |
          cd frontend
          cargo make appflowy-flutter-deps-tools

      - name: Build APK
        script: |
          cd frontend/appflowy_flutter
          flutter pub get
          flutter build apk --debug

    artifacts:
      - frontend/appflowy_flutter/build/**/outputs/**/*.apk